### ISSUE TITLE
SSHTarget not found in release 0.9.0

### ISSUE THREAD

**Issue by fghawi** [SUSE/salt-netapi-client#182]
Hello,
SSHTarget is used in some the examples provided, but it's not found in release 0.9.0 jar.
What am I missing here?
Thanks.

**Comment by lucidd** [comment]
Hey,
The examples are always in sync with the rest of the code. So when you look at the master branch you will see examples using code from the master branch which is potentially in no release yet.

To see the examples for a particular version checkout the tag for that version and look at the examples there. 

For example https://github.com/SUSE/salt-netapi-client/tree/v0.9.0/src/test/java/com/suse/salt/netapi/examples.

Happy Holidays!

**Comment by renner** [comment]
@fghawi: The `SSHTarget` interface was added after the release of version 0.9.0, it will be included with the next release. If you are looking for Salt SSH example code that works with 0.9.0 then please [check out the 0.9.0 tag](https://github.com/SUSE/salt-netapi-client/blob/v0.9.0/src/test/java/com/suse/salt/netapi/examples/SaltSSH.java) accordingly.

Note that `SSHTarget` is not needed to issue calls via Salt SSH, see 59789c76c0cd4a36450195dfb7662b9d099a31c4. There is also the complete [list of all the commits to master since the release of 0.9.0](https://github.com/SUSE/salt-netapi-client/compare/v0.9.0...master), in case you want to work with these changes before the next release feel free to build a `0.10.0-SNAPSHOT` jar using `mvn` locally.
