### ISSUE TITLE
How to change the timezone of master or api?

### ISSUE THREAD

**Issue by wzlee** [SUSE/salt-netapi-client#249]
The server's timezone is right,But the token's date is wrong timezone:
 ```shell
[root@localhost ~]# date -R
Tue, 22 Jan 2019 18:00:03 +0800
[root@localhost ~]# 
```
```json
{
    "return": [
        {
            "perms": [
                ".*",
                "@runner",
                "@wheel",
                "@jobs"
            ],
            "start": 1548151789.604669,
            "token": "fb7d8ca56f76485f735312b1eb9dd31a602f6e3d",
            "expire": 1548194989.60467,
            "user": "leo",
            "eauth": "mysql"
        }
    ]
}
```
![image](https://user-images.githubusercontent.com/4182865/51528366-784d9980-1e71-11e9-97bc-e9d1313a2e2d.png)

So, How I can change the timezone of salt to my timezone?

**Comment by wzlee** [comment]
Is any one can help me?

**Comment by lucidd** [comment]
@wzlee this sounds like a generic salt question. Since i don't know the answer to this i think its better to ask this on the saltstack github https://github.com/saltstack/salt.

**Comment by dmacvicar** [comment]
@wzlee Can you reproduce this without the Java client? (eg. pure curl or httpie calls?)

**Comment by renner** [comment]
@wzlee Is this still a problem for you? To me this seems to be a timestamp that needs to be converted to the correct timezone on the client side, i.e. when you are calling `new Date()`. I am closing the issue as there was no response from you since a long time, but feel free to reopen it in case you suspect an issue with the library.
